// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bjorbeuuczqfcckoghfk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJqb3JiZXV1Y3pxZmNja29naGZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMjcxOTIsImV4cCI6MjA3MTgwMzE5Mn0.rbwe4p1lv8JCH07MpNxXUXkwK2wVuMZ0x7sPBS-LOLk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});